### ISSUE TITLE
pledges don't add up and update

### ISSUE THREAD

**Issue by leb0guy** [MattrAus/Groupbuy-Coordinator#1]
when adding pledge, max is $99, and if you write $99 and someone else writes $20 the pledge price below doesn't add 99+30, but it just changes the pledge to $30/$$$$$

**Comment by MattrAus** [comment]
I've committed two changes:

1. Force package to use discord.js@13.15.1 [#699eb7a](https://github.com/MattrAus/Groupbuy-Coordinator/commit/699eb7a09b77407f7c121de67c1a95dd65773715)
2. Fixed currency for pledged and paid not using it's value (resulting in an object being stored) [#a54a827](https://github.com/MattrAus/Groupbuy-Coordinator/commit/a54a827f18e9c438613caf00b32c8f23996fc9f0)

Could you re-install and let me know if you face any issues?
